Update locales-pt-BR.xml
citation-style-language/locales pull request #251
Opened 2022-02-09 22:36 UTC by pirei

Hi! I want to collab with this document.

## CSL Locales Pull Request Template

You're about to create a pull request to the CSL locales repository.
If you haven't done so already, see <http://docs.citationstyles.org/en/stable/translating-locale-files.html> for instructions on how to translate CSL locale files, and <https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md> on how to submit your changes.
In addition, please fill out the pull request template below.

### Description

Briefly describe the changes you're proposing.

### Checklist

- [ ] Check that you're listed as a `<translator>` in the `<info>` block at the beginning of the file.

2022-04-19 17:26 UTC, bwiernik requested changes
Thanks! A few questions.

2023-03-23 02:08 UTC, adam3smith commented
OK, still some terms to translate left, but no reason to let the perfect the enemy of the obvious improvement here.

2023-03-23 02:08 UTC, merged

2023-04-17 18:16 UTC, guslaet commented
I just opened this issue about this file:

https://github.com/citation-style-language/locales/issues/284

Then I tried to fork it and propose the corrections, but the version it loaded was already corrected, so perhaps you have already seen it. It would be nice if these changes are merged.

2024-01-16 15:04 UTC, victormpalma commented on locales-pt-BR.xml
> +    <term name="thesis">Tese</term>
Is it possible to replace 'padrão' by 'norma técnica', which is the best translation for 'standard' in this context?

2024-01-16 18:00 UTC, pirei commented
> I just opened this issue about this file:
> 
> 
> 
> https://github.com/citation-style-language/locales/issues/284
> 
> 
> 
> Then I tried to fork it and propose the corrections, but the version it loaded was already corrected, so perhaps you have already seen it. It would be nice if these changes are merged.

I did some improvements but I was unable to find them.